language: c
compiler:
  - gcc
  - clang
# Change this to your needs
before_script: 
  - npm install webvtt
  - pwd
  - cd ./fuzz/zzuf/
  - ./bootstrap
  - make
  - cd
script: make check-js