language: c
compiler:
  - gcc
  - clang
# Change this to your needs
before_script: 
  - npm install webvtt
  - sudo apt-get update
  - sudo apt-get install zzuf
  - npm install ref ffi ref-struct
script: ./configure && make
after_script:
  - cp ./src/libwebvtt/.libs/libwebvtt.so ./test/unit
  - cp ./src/libwebvtt/.libs/libwebvtt.so.0 ./test/unit
  - cp ./src/libwebvtt/.libs/libwebvtt.so.0.0.0 ./test/unit
  - cp ./src/libwebvtt/.libs/libwebvtt.so ./node_modules/ffi/lib
  - cp ./src/libwebvtt/.libs/libwebvtt.so.0 ./node_modules/ffi/lib
  - cp ./src/libwebvtt/.libs/libwebvtt.so.0.0.0 ./node_modules/ffi/lib
  - cd ./src/
  - ls -lRa
  - cd ..
  - cd ./test/unit
  - ls -lRa
  - node libwebvtt.js