language: c
compiler:
  - gcc
  - clang
# Change this to your needs
before_script: 
  - npm install webvtt
  - sudo apt-get update
  - sudo apt-get install zzuf
  - npm install ref ffi ref-struct
  - npm install nodeunit
script: ./configure && make
after_script:
  - cd ./src/
  - ls -lRa
  - cd ..
  - cp ./src/libwebvtt/.libs/libwebvtt.so ./test/unit
  - cp ./src/libwebvtt/.libs/libwebvtt.so.0 ./test/unit
  - cp ./src/libwebvtt/.libs/libwebvtt.so.0.0.0 ./test/unit
  - cp ./src/libwebvtt/libwebvtt.a ./node_modules/ffi/lib
  - cp ./src/libwebvtt/.libs/libwebvtt.so ./node_modules/ffi/lib
  - cp ./src/libwebvtt/.libs/libwebvtt.so.0 ./node_modules/ffi/lib
  - cp ./src/libwebvtt/.libs/libwebvtt.so.0.0.0 ./node_modules/ffi/lib
  - cd ./test/unit
  - gcc -shared -fpic factorial.c -o libfactorial.so
  - ls -lRa  
  - node factorial.js 8
  - node libwebvtt.js