language: c
compiler:
  - gcc
  - clang
# Change this to your needs
before_script: 
  - npm install webvtt
  - pwd
  - sudo apt-get update
  - sudo apt-get install zzuf
  - which zzuf
script: make check-js
after_script:
  - cd ./fuzz
  - ./fuzzv2.script 0.1