language: c
compiler:
  - gcc
  - clang
# Change this to your needs
before_script: 
  - npm install webvtt
  - pwd
  - sudo apt-get update
  - sudo apt-get install zzuf
  - ls
  - zzuf
  - make
  - cd
script: make check-js