language: c

compiler:
  - gcc

before_install:
  - sudo apt-get install valgrind

script: ./bootstrap.sh && ./configure --enable-valgrind-testing && make && make check

notifications:
  email:
    - david.humphrey@senecacollege.ca

  irc: "irc.mozilla.org#seneca"
